name: Preprocessing Diabetes Dataset

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn numpy

      - name: Jalankan preprocessing
        run: |
          cd preprocessing
          python automate_Haikal.S.py

      - name: Commit dan push hasil preprocessing
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add preprocessing/diabetes_train.csv
          git add preprocessing/diabetes_test.csv
          git commit -m "Auto preprocessing - ${{ github.run_number }}"
          git push